config/routes.rb
Rails.application.routes.draw do
  resources :people do
    resources :interactions, only: [:new, :create, :edit, :update ]
  end
  resources :businesses do
    resources :interactions, only: [:new, :create, :edit, :update ]
  end
  root to: "people#index"
end

app/models/business.rb
class Business < ActiveRecord::Base
	has_many :interactions, as: :interactive
end

app/models/interaction.rb
class Interaction < ActiveRecord::Base
  belongs_to :interactive, polymorphic: true
end

app/models/person.rb
class Person < ActiveRecord::Base
	has_many :interactions, as: :interactive

	def name
		"#{first_name} #{last_name}"
	end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/businesses_controller.rb
class BusinessesController < ApplicationController
  def index
    @businesses = Business.all
  end

  def show
    @business = Business.find(params[:id])
  end

  def new
    @business = Business.new
  end

  def create
    @business = Business.new(business_params)

    if @business.save
      redirect_to businesses_path, notice: "The business has been successfully created."
    end
  end

  def edit
    @business = Business.find(params[:id])
  end

  def update
    @business = Business.find(params[:id])
    if @business.update_attributes(business_params)
      redirect_to businesses_path, notice: "The business has been updated"
    end
  end

  def destroy
    @business = Business.find(params[:id])
    @business.destroy
  end
private
  def business_params
    params.require(:business).permit!
  end
end

app/controllers/interactions_controller.rb
class InteractionsController < ApplicationController
  def new
    @context = context
    @interaction = @context.interactions.new
  end

  def create
    @context = context
    @interaction = @context.interactions.new(interaction_params)

    if @interaction.save
      redirect_to context_url(context), notice: "The interaction has been successfully created."
    end
  end

  def edit
    @context = context
    @interaction = context.interactions.find(params[:id])
  end

  def update
    @context = context
    @interaction = @context.interactions.find(params[:id])
    if @interaction.update_attributes(interaction_params)
      redirect_to context_url(context), notice: "The interaction has been updated"
    end
  end

private
  def interaction_params
    params.require(:interaction).permit!
  end

  def context
    if params[:person_id]
      id = params[:person_id]
      Person.find(params[:person_id])
    else
      id = params[:business_id]
      Business.find(params[:business_id])
    end
  end 

  def context_url(context)
    if Person === context
      person_path(context)
    else
      business_path(context)
    end
  end
end

app/controllers/people_controller.rb
class PeopleController < ApplicationController
  def index
    @people = Person.all
  end

  def show
    @person = Person.find(params[:id])
  end

  def new
    @person = Person.new
  end

  def create
    @person = Person.new(person_params)

    if @person.save
      redirect_to people_path, notice: "The person has been successfully created."
    end
  end

  def edit
    @person = Person.find(params[:id])
  end

  def update
    @person = Person.find(params[:id])
    if @person.update_attributes(person_params)
      redirect_to people_path, notice: "The person has been updated"
    end
  end

  def destroy
    @person = Person.find(params[:id])
    @person.destroy
  end
private
  def person_params
    params.require(:person).permit!
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/businesses_helper.rb
module BusinessesHelper
end

app/helpers/interactions_helper.rb
module InteractionsHelper
end

app/helpers/people_helper.rb
module PeopleHelper
end

app/views/businesses/_form.html.erb
<%= form_for @business do |f| %>
  <div class="form-group">
    <%= f.label :name %>
    <%= f.text_field :name, class: "form-control", placeholder: "Enter the name of the business" %>
  </div>
  <%= f.submit class: "btn btn-primary" %>
<% end %>

app/views/businesses/create.html.erb
<h1>Businesses#create</h1>
<p>Find me in app/views/businesses/create.html.erb</p>

app/views/businesses/edit.html.erb
<h1>Edit Business</h1>
<%= render "form" %>

app/views/businesses/index.html.erb
<h1>Businesses</h1>
<div class="well">
<%= link_to "New Business", new_business_path, class: "btn btn-primary" %>
</div>
<table class="table table-bordered table-striped">
  <thead>
    <tr>
      <th>Name</th>
      <th>Number of Interactions</th>
      <th>&nbsp;</th>
    </tr>
  </thead>
  <tbody>
    <% if @businesses.count == 0 %>
      <tr>
        <td colspan="3">
          No businesses found.  Click the button above to add a new one.
        </td>
      </tr>
    <% else %>
      <% @businesses.each do |business| %>
        <tr>
          <td><%= link_to business.name, business %></td>
          <td><%= business.interactions.count %></td>
          <td><%= link_to "Edit", edit_business_path(business), class: "btn btn-default" %></td>
        </tr>
      <% end %>
    <% end %>
  </tbody>
</table>

app/views/businesses/new.html.erb
<h1>Create a New Business</h1>
<%= render "form" %>

app/views/businesses/show.html.erb
<h1><%= @business.name %></h1>
<hr />
<h3>Interactions</h3>
<div class="well">
  <%= link_to "New Interaction", new_business_interaction_path(@business), class: "btn btn-primary" %>
</div>
<table class="table table-bordered table-striped">
  <thead>
    <tr>
      <th>Description</th>
      <th>Created On</th>
      <th>&nbsp;</th>
    </tr>
  </thead>
  <% if @business.interactions.count > 0 %>
    <% @business.interactions.each do |interaction| %>
      <tr>
        <td><%= interaction.description %></td>
        <td><%= time_ago_in_words interaction.created_at %> ago</td>
        <td><%= link_to "Edit", edit_business_interaction_path(@business, interaction), class:"btn btn-default" %></td>
      </tr>
    <% end %>
  <% else %>
    <tr>
      <td colspan="2">No interactions found for this business.  Click the 'New Interaction' button to create a new interaction.</td>
    </tr>
  <% end %>
</table>

app/views/businesses/update.html.erb
<h1>Businesses#update</h1>
<p>Find me in app/views/businesses/update.html.erb</p>

app/views/interactions/_form.html.erb
<%= form_for [@context, @interaction] do |f| %>
  <div class="form-group">
    <%= f.label :description %>
    <%= f.text_area :description, class: "form-control", placeholder: "Enter a description of the interaction you had with this entity.", rows: 10 %>
  </div>

  <%= f.submit class: "btn btn-primary" %>
<% end %>

app/views/interactions/create.html.erb
<h1>Interactions#create</h1>
<p>Find me in app/views/interactions/create.html.erb</p>

app/views/interactions/edit.html.erb
<h1>Editing Interaction for <%= @context.name %></h1>
<%= render "form" %>

app/views/interactions/new.html.erb
<h1>New Interaction for <%= @context.name %></h1>
<%= render "form" %>

app/views/interactions/update.html.erb
<h1>Interactions#update</h1>
<p>Find me in app/views/interactions/update.html.erb</p>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
	<head>
	  <title>PolymorphicExample</title>
	  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
	  <%= stylesheet_link_tag "http://yandex.st/bootstrap/3.0.2/css/bootstrap.min.css", media: "all" %>
	  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
	  <%= javascript_include_tag "http://yandex.st/bootstrap/3.0.2/js/bootstrap.min.js" %>
	  <%= csrf_meta_tags %>
	</head>
	<body>
	  <nav class="navbar navbar-inverse navbar-static-top">
	    <div class="container">
	      <ul class="nav navbar-nav">
	        <li><%= link_to "People", people_path %></li>
	        <li><%= link_to "Businesses", businesses_path %></li>
	      </ul>
	    </div>
	  </nav>
	   
	  <div class="container">
	    <%= yield %>
	  </div>

	</body>
</html>

app/views/people/_form.html.erb
<%= form_for @person do |f| %>
  <div class="form-group">
    <%= f.label :first_name %>
    <%= f.text_field :first_name, class: "form-control", placeholder: "Enter a First Name" %>
  </div>
  <div class="form-group">
    <%= f.label :last_name %>
    <%= f.text_field :last_name, class: "form-control", placeholder: "Enter a Last Name" %>
  </div>
  <%= f.submit class: "btn btn-primary" %>
<% end %>

app/views/people/create.html.erb
<h1>People#create</h1>
<p>Find me in app/views/people/create.html.erb</p>

app/views/people/edit.html.erb
<h1>Editing <%= @person.name %></h1>
<%= render "form" %>

app/views/people/index.html.erb
<h1>People</h1>
<div class="well">
<%= link_to "New Person", new_person_path, class: "btn btn-primary" %>
</div>
<table class="table table-bordered table-striped">
  <thead>
    <tr>
      <th>Name</th>
      <th>Number of Interactions</th>
      <th>&nbsp;</th>
    </tr>
  </thead>
  <tbody>
    <% if @people.count == 0 %>
      <tr>
        <td colspan="3">
          No people found.  Click the button above to add a new one.
        </td>
      </tr>
    <% else %>
      <% @people.each do |person| %>
        <tr>
          <td><%= link_to "#{person.first_name} #{person.last_name}", person %></td>
          <td><%= person.interactions.count %></td>
          <td><%= link_to "Edit", edit_person_path(person), class: "btn btn-default" %></td>
        </tr>
      <% end %>
    <% end %>
  </tbody>
</table>

app/views/people/new.html.erb
<h1>Create a New Person</h1>
<%= render "form" %>

app/views/people/show.html.erb
<h1><%= "#{@person.first_name} #{@person.last_name}" %></h1>
<hr />
<h3>Interactions</h3>
<div class="well">
  <%= link_to "New Interaction", new_person_interaction_path(@person), class: "btn btn-primary" %>
</div>
<table class="table table-bordered table-striped">
  <thead>
    <tr>
      <th>Description</th>
      <th>Created On</th>
      <td>&nbsp;</td>
    </tr>
  </thead>
  <% if @person.interactions.count > 0 %>
    <% @person.interactions.each do |interaction| %>
      <tr>
        <td><%= interaction.description %></td>
        <td><%= time_ago_in_words interaction.created_at %> ago</td>
        <td><%= link_to "Edit", edit_person_interaction_path(@person, interaction), class: "btn btn-default" %></td>
      </tr>
    <% end %>
  <% else %>
    <tr>
      <td colspan="2">No interactions found for this person.  Click the 'New Interaction' button to create a new interaction.</td>
    </tr>
  <% end %>
</table>

app/views/people/update.html.erb
<h1>People#update</h1>
<p>Find me in app/views/people/update.html.erb</p>